[tool.poetry]
name = "project-tst"
version = "0.1.0"
description = ""
authors = ["Martin Petri Bagger <bagger@econ.au.dk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
